services :
  mmb-node-exporter:
    image: prom/node-exporter
    container_name: mmb-node-exporter
    restart: no
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    networks:
      - mumulbo-network

  mmb-process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: mmb-process-exporter
    restart: no
    volumes:
      - /proc:/host/proc:ro
      - ./exporters/process-exporter.yml:/etc/process-exporter/config.yml:ro
      - /etc:/host/etc:ro
    command:
      - "--procfs=/host/proc"
      - "--config.path=/etc/process-exporter/config.yml"
    ports:
      - "${PROCESS_EXPORTER_PORT}:9256"
    networks:
      - mumulbo-network

  mmb-prometheus:
    image: prom/prometheus
    container_name: mmb-prometheus
    restart: no
    depends_on:
      - mmb-node-exporter
      - mmb-process-exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - mumulbo-network

  mmb-grafana:
    image: grafana/grafana
    container_name: mmb-grafana
    restart: no
    depends_on:
      - mmb-prometheus
    environment:
      - GF_SERVER_ROOT_URL=https://localhost:3000/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - mumulbo-network

  mmb-loki:
    image: grafana/loki
    container_name: mmb-loki
    restart: no
    user: "0:0"
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - mumulbo-network

#  mmb-promtail:
#    image: grafana/promtail
#    container_name: mmb-promtail
#    restart: no
#    volumes:
#      - /var/log:/var/log:ro  # 호스트의 로그 읽기
#      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
#    command: -config.file=/etc/promtail/config.yaml
#    networks:
#      - mgt-net

  mmb-fluentbit:
    image: grafana/fluent-bit-plugin-loki
    platform: linux/amd64
    container_name: mmb-fluentbit
    ports:
      - "${FLUENTBIT_LOKI_PORT}:24224"  # Fluent Bit forward input 포트
      - "${FLUENTBIT_PORT}:2020"  # Fluent Bit 상태 확인 포트
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/extract_tag.lua:/fluent-bit/scripts/extract_tag.lua:ro
    networks:
      - mumulbo-network 

volumes:
  grafana_data:
    external: true
  prometheus_data:
  loki_data:

networks:
  mumulbo-network:
    external: true
    driver: bridge
    name: ${MMB_DOCKER_NETWORK}
