services :
  mmb-node-exporter:
    image: prom/node-exporter
    container_name: mmb-node-exporter
    restart: no
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    networks:
      - mgt-net
      - be-net

  mmb-process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: mmb-process-exporter
    restart: no
    volumes:
      - /proc:/host/proc:ro
      - ./exporters/process-exporter.yml:/etc/process-exporter/config.yml:ro
      - /etc:/host/etc:ro
    command:
      - "--procfs=/host/proc"
      - "--config.path=/etc/process-exporter/config.yml"
    ports:
      - "${PROCESS_EXPORTER_PORT}:9256"
    networks:
      - mgt-net
      - be-net

  mmb-prometheus:
    image: prom/prometheus
    container_name: mmb-prometheus
    restart: no
    depends_on:
      - mmb-node-exporter
      - mmb-process-exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - mgt-net

  mmb-grafana:
    image: grafana/grafana
    container_name: mmb-grafana
    restart: no
    depends_on:
      - mmb-prometheus
    environment:
      - GF_SERVER_ROOT_URL=https://localhost:3000/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - mgt-net

  mmb-loki:
    image: grafana/loki
    container_name: mmb-loki
    restart: no
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - mgt-net

  mmb-promtail:
    image: grafana/promtail
    container_name: mmb-promtail
    restart: no
    volumes:
      - /var/log:/var/log:ro  # 호스트의 로그 읽기
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - mgt-net

volumes:
  grafana_data:
    external: true
  prometheus_data:
  loki_data:

networks:
  be-net:
    driver: bridge
  mgt-net:
    driver: bridge
