global:
  scrape_interval: 60s   # 모든 타겟에 대해 1분마다 메트릭 수집

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['${NODE_EXPORTER}:9100']
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['${PROCESS_EXPORTER}:9256']
